# docker-compose.yml
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    restart: unless-stopped
    environment:
      SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - sqlserver:/var/opt/mssql/

    entrypoint: /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 30 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password123! -i /docker-entrypoint-initdb.d/init.sql &&
      wait"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: mssql
    ports:
      - "8080:8080"
volumes:
  sqlserver:
